version: '3'
services:
  app-minesweeper:
    image: nalleon14716/app-minesweeper-image
    container_name: app-minesweeper-container
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
#    volumes:
#      - .:/var/www
    networks:
      - app-minesweeper-network

  app-minesweeper-webserver:
    image: nalleon14716/app-minesweeper-nginx-webserver-image
    container_name: app-minesweeper-nginx-webserver
    restart: unless-stopped
    ports:
      - "9092:80"
#    volumes:
#     - .:/var/www
#      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - app-minesweeper-network
volumes:
  app-minesweeper-dbdata:
networks:
  app-minesweeper-network: